"""Páramo Urbano Core Domain Layer.

Exposes domain models, value objects, exceptions, and canonical records
isolated from frameworks, ORMs, and persistence mechanisms.
"""

from .exceptions import (
    AuthenticationError,
    BiometricConstraintViolationException,
    CorruptedFileException,
    CorruptedFitFileException,
    DomainError,
    DuplicateActivityException,
    EntityNotFoundError,
    EntityValidationError,
    GoalRuleViolationError,
    InvalidElevationError,
    InvalidFitHeaderException,
    InvalidHashError,
    InvalidHeartRateError,
    InvalidLoadError,
    InvalidRPEError,
    InvalidSpeedError,
    InvalidTargetDateException,
    InvalidVDOTError,
    ParserError,
    PhysiologicalBoundError,
    PhysiologicalCalculationError,
    SecurityXmlAttackException,
    UnsupportedFileFormatException,
    ZeroDivisionWorkloadError,
)
from .models import (
    Activity,
    Athlete,
    AthleteProfile,
    CanonicalActivityRecord,
    Discipline,
    Elevation,
    ExperienceLevel,
    Goal,
    HeartRate,
    ProcessingStatus,
    RawTelemetryPoint,
    SessionRPE,
    Sha256Hash,
    SourceType,
    Speed,
    SportCategory,
    SubgoalType,
)
from .physiological import (
    ACWREvaluator,
    ACWRStatus,
    ACWRZone,
    AltitudeHysteresisFilter,
    BanisterModel,
    ElevationGainResult,
    LoadCalculationMethod,
    PaceZone,
    SessionLoad,
    SessionLoadCalculator,
    VDOTCalculator,
    VDOTPrescription,
    WorkloadMetrics,
)

__all__ = [
    # Exceptions
    "DomainError",
    "AuthenticationError",
    "BiometricConstraintViolationException",
    "DuplicateActivityException",
    "EntityNotFoundError",
    "InvalidTargetDateException",
    "PhysiologicalBoundError",
    "PhysiologicalCalculationError",
    "ZeroDivisionWorkloadError",
    "InvalidHeartRateError",
    "InvalidElevationError",
    "InvalidSpeedError",
    "InvalidRPEError",
    "InvalidHashError",
    "InvalidLoadError",
    "InvalidVDOTError",
    "GoalRuleViolationError",
    "EntityValidationError",
    "ParserError",
    "InvalidFitHeaderException",
    "CorruptedFitFileException",
    "SecurityXmlAttackException",
    "UnsupportedFileFormatException",
    "CorruptedFileException",
    # Models
    "Activity",
    "CanonicalActivityRecord",
    "Athlete",
    "AthleteProfile",
    "Goal",
    "HeartRate",
    "Elevation",
    "Speed",
    "SessionRPE",
    "Sha256Hash",
    "RawTelemetryPoint",
    "Discipline",
    "SubgoalType",
    "SportCategory",
    "SourceType",
    "ProcessingStatus",
    "ExperienceLevel",
    # Physiological Engine
    "BanisterModel",
    "WorkloadMetrics",
    "ACWREvaluator",
    "ACWRStatus",
    "ACWRZone",
    "SessionLoadCalculator",
    "SessionLoad",
    "LoadCalculationMethod",
    "AltitudeHysteresisFilter",
    "ElevationGainResult",
    "VDOTCalculator",
    "VDOTPrescription",
    "PaceZone",
]
